# Site settings
title: volkannnn
description: 'import thisnnn'
url: 'http://volkansah.in'
baseurl: '/blog/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Volkan Sahinnnn'
  email: bm.volkansahinnnn@gmail.com
  twitter_username: volkansahinnnnn
  facebook_username: bm.volkansahinnnn
  github_username:  volkansahinnnn
  linkedin_username:  volkansahinnn

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: :/year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
