# Site settings
title: volkansahin
description: 'import this'
url: 'volkansah.in'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Volkan Şahin'
  email: bm.volkansahin@gmail.com
  twitter_username: volkansahinnnnn
  facebook_username: bm.volkansahin
  github_username:  volkansahin
  linkedin_username:  volkansahin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
